### ISSUE TITLE
WalletConnect error for unsupported actions

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#1263]
Receiving an unsupported WalletConnect action puts the user into a restart loop.

<img src="https://images.zenhubusercontent.com/5f8d54cb717387f606ed5dce/e939592d-0173-47ad-ae78-02cd88856460" width="50%" />

See [Slack thread](https://valora-app.slack.com/archives/C01CN6AUHGX/p1634136623094100). 

Steps to reproduce:
1. Connect Valora with WalletConnect on https://app.sushi.com/swap
2. Once connect, go back to the brwoser
3. Click on the "Limit" tab and select "Polygon"
<img width="1497" alt="Screenshot 2021-10-14 at 09 32 18" src="https://user-images.githubusercontent.com/57791/137272856-a972a8d8-ffc4-49df-9443-3e6e4792e70c.png">

4. Go back to Valora
5. See error screen
6. quit and restart the app
7. error screen is displayed again

**Comment by ValoraQA** [comment]
Hey @jeanregisser, We have verified this issue using Latest Test Flight build V1.21.0 & observed that issue is fixed now. Also we have updated status in below sheet.
**Gsuite Link:** https://docs.google.com/spreadsheets/d/10NvmhuwUv7r-_SYZPsvGcLOyRZg3dlQpDk8n5JSSm8s/edit#gid=1669471716&range=O3
**Verified On Devices:**  iPhone 12(14.7.1)
**Verified On Browser:**  Microsoft Edge V93.0

CC: @MuckT
