### ISSUE TITLE
Tapping Deny on WC / Dapp Connection Screen on Fresh Install Shows Invalid Homescreen

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1426]
### Current behavior

For users who freshly install Valora and attempt to connect to a Dapp, without first setting up their account, if they deny the Dapp connection prompt they arrive at an empty homescreen. 

### Desired behavior

The user if the account is not setup we don't try to open the deeplink or connect with WalletConnect ws url with Valora.

### Steps to Reproduce
**Perquisites**  On a fresh install or reset account that has not completed onboarding.

1. Navigate to a service using WC or a deeplink e.g. [PoolTogether](https://pooltogether.com/) or [Sushi](https://sushi.com/)
2. Connect to Valora
3. Deny the Connection in Prompt

### Video

https://user-images.githubusercontent.com/26950305/141374361-6d8a49d6-0fe1-41b2-a964-934c7baa51ad.mov

### Workaround
- Closing and reopening the app takes the user back to the first step of onboarding.

### Versions

v1.21.0

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Play store build V1.21.0, App store build V1.21.0 & observed the issue is reproducible. 

**Observation:**
- When user clicks on "Allow" button from wallet connect prompt it loads continuously, Cancel button, allow button is not clickable & on clicking cancel "X" button connecting screen appears. [Attachment](https://drive.google.com/file/d/1yZQ9aFhwsqYWbPOOIcWn3NksqQ1xYtXI/view?usp=sharing)

**Devices:** One plus 7T(11.0), Redmi Note 8 (10.0), iPhone 12(15.0)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Internal Release build V1.24.1, iOS TestFlight Release build V1.24.1 and observed that issue is faced for "https://mento-fi-q5d61619k-celotools.vercel.app/" too 

Observation:

-When user clicks on "Allow" button from wallet connect prompt , loader is seen continuously
-Cancel button, allow button both are not clickable after loader is seen
-Clicking on "X" button in top left navigates user to connecting screen.
Attachment: (mentoissue1.mp4)[]

Devices: Google Pixel 2XL(11.0), iPhone 12(14.7.1)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Internal Release build V1.24.1, iOS TestFlight Release build V1.24.1 and observed that issue is faced for "https://mento-fi-q5d61619k-celotools.vercel.app/" too

**Observation:**
- When user clicks on "Allow" button from wallet connect prompt , loader is seen continuously
- Cancel button, allow button both are not clickable after loader is seen
- Clicking on "X" button in top left navigates user to connecting screen and then redirets user to home page where account address is not seen 

**Attachment**: (mentoissue1.mp4)[https://drive.google.com/file/d/1HL5GkqORJotBQFCI-_RRH77u5tKXebQE/view?usp=sharing]

**Devices**: Google Pixel 2XL(11.0), iPhone 12(14.7.1)
Thanks..!!

**Comment by MuckT** [comment]
This issue is no longer valid with the use of the Dapp Bottom Sheet.

https://user-images.githubusercontent.com/26950305/193930083-10c24fdf-687f-4423-8a9f-2f14c0ef5bf1.mov
