### ISSUE TITLE
[M2] Create Account Token & Finclusive Counter-Party

### ISSUE THREAD

**Issue by jh2oman** [valora-inc/wallet#1448]
Create an account token with Plaid and retrieved an institutions information and then call IHL to save that info with Finclusive.

AC:
* call the POST /plaid/access-token/exchange IHL endpoint to create an account token
* Call the IHL POST /account/counter-party endpoint at the end of the Plaid Link onSuccess hook
* Handle any errors, log them and display the error to the user.

**Comment by cajubelt** [comment]
@jh2oman I just noticed that there's an AC missing, and added it. We'll need to query plaid for bank account data before we can provide that to finclusive to create a counter-party account. This was missing from the account creation flow chart, too, so it's understandable that it got missed.

The plaid endpoint is documented here https://plaid.com/docs/api/accounts/#accountsget . I suggest we create a new IHL endpoint for this, since the plaid api secret is a required parameter. 

I'll create the issue and reference it as a blocker. Lmk if you want to discuss it though

**Comment by cajubelt** [comment]
actually, after doing some research on identity verification via plaid, I think we should update the IHL api to provide an access token to the `POST /account/bank-account` endpoint. That way, there is no additional roundtrip api call from the mobile client to get bank account details from Plaid via IHL, and identity verification becomes much easier (since it requires an access token and is hard to do in a separate step from getting bank account details).

**Comment by cajubelt** [comment]
it's safe to provide an access token for linking a single bank account because the user can choose only 1 account in the Link flow (with our present configuration)
