### ISSUE TITLE
Confirming invites display incorrectly in feed

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1491]
###Current behavior
After inviting a user while the confirmation is pending invites display a large incorrect value in the feed.

### Desired behavior
While confirmation is occurring invites should display the correct value or no value at all; invite rewards should not display a large incorrect value.

### Steps to Reproduce
1. On an existing account with a balance send an invite to a new user
2. Complete invite flow and observe transaction in the feed while pending.

### Versions
v1.22.1x

**Comment by ValoraQA** [comment]
Hey @MuckT We have observed the same issue. 
- [ ] User able to see a large amount on "Recent" feed after sending an invite to User B for some time. We have a ticket [#1495](https://github.com/valora-inc/wallet/issues/1495) for the same.
Thanks..!!

**Comment by MuckT** [comment]
@ValoraQA please retest on the next release or hot fix.

**Comment by ValoraQA** [comment]
> @ValoraQA please retest on the next release or hot fix.

Sure @MuckT we will retest it when we got the next release/hotfix & will  update you here

**Comment by ValoraQA** [comment]
Hi, @MuckT we have verified the above issue on latest android internal build V:1.22.1 and latest iOS test flight and observed that issue is still reproducible 

**Observation :** We are still able to see the large amount on the homepage in recent activity section after inviting another user 
**Attachment :** [invite_issue.jpg](https://drive.google.com/file/d/12dBcRNZjskpXI_3rCATVS2Niiyl1I1Tt/view?usp=sharing)

**Verified on devices :** OnePlus 7t(11.0) , iPhone 6+(12.5.4) , Redmi Note 8(9.0)
