### ISSUE TITLE
Operation Translations Failing to Populate in WalletConnect

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1557]
### Current behavior
Operation translations are failing to populate in Wallet Connect.

### Desired behavior
Operation translations should be present on the Wallet Connect `ActionRequest.tsx` screen.

### Steps to Reproduce
1. Connect to a Dapp using WalletConnect like [PoolTogether](https://app.pooltogether.com/).
2. Accept the session.
3. Attempt to perform an action that would trigger the `ActionsRequest.tsx` screen e.g. adding to a pool.
4. Observe section under 'Operation' is not populated.

### Screenshot
<img src="https://user-images.githubusercontent.com/26950305/144338460-f836156c-c107-4c2c-9bc5-1f37e5b8ce84.png" alt="Wallet Connect Action Request" width="50%" height="auto">

### Versions
v1.22.2 & v1.22.3 Does not reproduce on 1.21.0

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Test flight build V:1.22.4 and observed that issue is fixed now.
Observation: 
- "Send a CELO tx" text is displayed under the operation section and also after tapping on "Allow"  button the transaction is completed successfully.
**Device:** iPhone XR(14.6), iPhone SE(13.6.1)
**Attachments:** 
[Operation Section text.jpg](https://drive.google.com/file/d/1UjfjS_4ji5nzEY5sY-zif_hGg_qdtHXu/view?usp=sharing)
[Transaction Successfull.jpg](https://drive.google.com/file/d/1DQYhkodqu1MacxNl61nfnRFJ3J9yK_iH/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have commented in the ticket #1563
