### ISSUE TITLE
Unable to send max amount when user has one token

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1648]
### Current behavior
When attempting to send the max amount, if user only has one token, it appears that fee's are not included and the send fails.

### Desired behavior
Fee's should be included calculating the max amount when sending.

### Steps to Reproduce
Perquisites - Send some funds to a new wallet or use one with a low balance.
1. On a wallet with low balance enter the send flow swap to a token display e.g. cUSD, cEUR, CELO etc.
2. Tap max.
3. Tap review.
4. Observe transaction revert in logs.

### Versions
Valora 1.24.x - Current main branch likely introduced by #1517 🤦 

### Notes
When sending and multiple account balances are present it appears that fees are pulled from other balances; however, when attempting to send a token and only one token is present in the wallet the transaction revert happens.

```
Possible Unhandled Promise Rejection (id: 0):
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xdb33a14695e980ff3529f9ac0d1d26d5e1bbab4c94e8fb9241a84da291f9775f",
  "blockNumber": 8923432,
  "contractAddress": null,
  "cumulativeGasUsed": 86035,
  "from": "0x18bf1905bc915b27ce15e5ef1149d21a9b76a638",
  "gasUsed": 24626,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xf194afdf50b03e69bd7d057c1aa9e10c9954e4c9",
  "transactionHash": "0xf5ff4f43c7978ab4df4c84cfb688a5737d5616ee327a<…>
```

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android alfajores nightly build V1.23.0 ,  iOS Alfajores nightly build V1.23.0 & observed that the issue is reproducible for first time sending transaction fails and from second time it gets executed by tapping on Max button.

**Observation:**
- For newly created account having cUSD balance of $1 only one token balance, if we try send amount by tapping on Max button , the transaction of sending $1 fails.
- When we try to send again second time, by tapping on max button the transaction gets completed for $0.99.

**Attachment:** [Max Transaction fails first time.mp4] (https://drive.google.com/file/d/1Pv4XoKL0hGthHBChtmUVJIpP7X_zcLII/view?usp=sharing) 
**Devices:** One plus 7t (11.0), iPhone 13 mini (15.1.1)
Thanks..!!

**Comment by MuckT** [comment]
Duplicate of #1585.
