### ISSUE TITLE
Allow sending comments for cUSD/cEUR/cREAL

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#1767]
### What would you like?
The new multi token flow is not allowing to add a comment with cUSD/cEUR/cREAL tokens. We should allow this!

**Comment by ValoraQA** [comment]
Hey @MuckT we have added our observation in the ticket #1769

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified this issue using iOS Appstore build V:1.24.1 and Android Playstore build V:1.24.1 and observed that issue is not reproducible

Observation : User is able to send money to another user with description added and it is visible in the transaction feed 
Devices : Google Pixel 2XL (11.0) , iPhone 12 (14.7.1)
attachment : [iOSworksfine.mp4](https://drive.google.com/file/d/1G8rIMHnhbgIQ4mw3JJz9h5fYCUOWXsvL/view?usp=sharing)
