### ISSUE TITLE
Pressing Back on Bidali from the Dapps Explorer page takes users back to Add and Withdraw

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#1818]
### Current behavior
Users who press back on the Bidali web-view are always navigated back to Add and Withdraw.

### Desired behavior
Pressing back should take users to the previous page used (in both cases that use the Bidali screen)

### Steps to Reproduce
1. Go to the Dapps Explorer
2. Tap Bidali
3. Tap Back from the Bidali webview

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue on Latest Android Internal Release Build , Latest iOS Test Flight Build V:1.24.1 , Android Playstore Build V:1.23.3 and observed that

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue on Latest Android Internal Release Build , Latest iOS Test Flight Build V:1.24.1 , Android Playstore Build V:1.23.3 and observed that

**Observation :** 
**For Android** 
- If we click on Done button then we are redirected to Add and Withdraw funds landing page 
- If we click on device back or gesture device back then it is redirecting to previous page 
Attachment : [Android.mp4](https://drive.google.com/file/d/19Z302nrGgBWZc9v1Ayni-MTopQkoBBT7/view?usp=sharing)

**For iOS:** 
- If we click on Done button then we are redirected to Add and Withdraw funds landing page 
- If we swipe the screen from LHS then it is redirecting to previous page
Attachment : [iOS.mp4](https://drive.google.com/file/d/1u9kinTvHnHc05jsUEuykpQWWgxjkxlGd/view?usp=sharing)

**Concern :** Can there be redirection to previous page if user clicks on done button.

**Checked on Devices :** OnePlus 7t(11.0) , Google Pixel 2XL(11.0) , iPhone 13 mini(15.1.1)

Thanks.!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Android Internal Release Build , Latest iOS Test Flight Build V:1.25.1 and observed that this issue is reproducible when user taps on Done button from bidali screen user is redirected to Add & withdraw screen.

**Observations :**
**For Android:**
- If we click on Done button then we are redirected to Add and Withdraw funds landing page
- If we click on device back or gesture device back then it is redirecting to previous page
- Attachment : [Android.mp4](https://drive.google.com/file/d/13JTsn5KR-siGF2mn2PWsK3D2lSA7enqR/view?usp=sharing)

**For iOS:**
- If we click on Done button then we are redirected to Add and Withdraw funds landing page
- If we swipe the screen from LHS then it is redirecting to previous page
- Attachment : [iOS.mp4](https://drive.google.com/file/d/1p2IGHbW6UQ6rRobPAbd3RfdT8KUSXvK7/view?usp=sharing)

**Devices:** OnePlus 7t(11.0) , Google Pixel 2XL(11.0) , iPhone 13 mini(15.1.1)
Thanks..!!
