### ISSUE TITLE
Bug: offline banner appears when user is online and doesn't go away

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1900]
Seems like the bug was introduced after 1.24 where the blue banner with the message that the user is offline doesn't go away (nor on hitting refresh, nor when the user has a connection again).
[Context on slack](https://valora-app.slack.com/archives/C018VLA3YAK/p1643389176624659)

[This issue ](https://app.zenhub.com/workspaces/retention-squad-sprint-board-612f2ef98ef2b800116e6043/issues/valora-inc/support-issues/71)might be related?

Expected behavior:
As soon as the user is online, the banner should go away by itself.

**Comment by ValoraQA** [comment]
Hey @aleksey-nov, We have verified the above task in Latest Android Internal Release build V:1.25.1 and Latest iOS test flight Release build V:1.25.1 & observed that this issue is only reproducible when user tries to change currency from settings screen, But the blue banner gets dismissed on it's own after it appears for some time.

**Query:**[1902](https://github.com/valora-inc/wallet/issues/1902) 
**Devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel 2XL(11.0)
**Attachments:** [Blue banner issue.mp4](https://drive.google.com/file/d/1F1DQjz9IXYnQaBfnV-t_vNjpEGK86slx/view?usp=sharing)
Thanks..!!
