### ISSUE TITLE
[Bug] Add funds current balance in the withdraw flow includes cUSD only.

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1908]
AC:
- [ ] Should reflect the total user's balance displayed on the home screen.

![135479520-915d9ebe-73bc-4973-ba2f-10cf34203e00.png](https://images.zenhubusercontent.com/60005dfc77558b950d71dca4/0cee9307-cea0-4b67-83ce-4ead25dbcea2)

**Comment by cajubelt** [comment]
should look at Gonza's work that reduces hardcoding on native tokens to calculate balance

**Comment by jh2oman** [comment]
We can't just directly take the Total Balance from home screen because of the conflict between the 'View Assets' button in the homescreen and the cute bird image from the Add/Withdraw screen. What should the solution be? Below are two easy options but feel free to come up with something else. 

### Option 1
![Simulator Screen Shot - iPhone 13 - 2022-02-07 at 14.13.31.png](https://images.zenhubusercontent.com/6185a7c8cdc62006d4e266fa/c1018450-a077-4896-aae5-044950ff9da3)

### Option 2
![Simulator Screen Shot - iPhone 13 - 2022-02-07 at 14.14.41.png](https://images.zenhubusercontent.com/6185a7c8cdc62006d4e266fa/f699e10b-19f4-4b04-a588-242df28ad350)

**Comment by nityarao** [comment]
Hey Jacob! WDYT of this? happy to explain the decision here if you wanna hop on a call! 
https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Support-for-Multiple-Tokens?node-id=1802%3A60858

**Comment by nityarao** [comment]
If the option in figma doesnt make sense, then I would advocate for option 2 above!

**Comment by jh2oman** [comment]
The design in figma should be quite simple! Can do
