### ISSUE TITLE
[FC UI] submit KYC info form UI

### ISSUE THREAD

**Issue by cajubelt** [valora-inc/wallet#1988]
As an end-user trying to cash in with an FC-compliant CICO provider, I need to be able to submit my information for KYC.

Eng:
- the fields can be hardcoded to some values we know we need (ideally an FC vendor like Paychant, but Finclusive if necessary)
- but some attention to flexibility should be built in so we can easily extend this to other KYC schemas

AC:
- user is able to submit info for KYC via a basic form UI

**Comment by jophish** [comment]
This is blocked by us deciding what mock KYC schema(s) we want to support in the FC API wrapper module for now. I suggest we just have a single mock KYC schema defined, probably something that requires e.g. name/dob/address and maybe id document/selfie?

In fact, the more I think about it, the more it seems like most of the UI work is blocked on us having FC typings available in the wallet; we don't need the FC API wrapper module _implemented_ per se, but we'll need typings available so that components can know what data they expect to receive as props.
