### ISSUE TITLE
Comments Not Appearing on cUSD and cEUR Payments

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2328]
### Current behavior
Comments Fail to appear on cUSD and cEUR transactions.

### Desired behavior
Comments should appear on cUSD and cEUR transactions in the transaction feed.

### Steps to Reproduce
1. Send a payment to an account with an attached comment
2. Observe the comment in the transaction feed.

### Versions
v1.30.x

https://user-images.githubusercontent.com/26950305/163634774-06451464-b0c1-4416-9de6-938ba9f32fbb.mov

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Android Internal Release Build V1.30.1 ,Test flight Release Build V ,Android Alfajores Build V1.30.1 & Test Flight Alfajores Build V1.30.1 and observed that the issue is not reproducible.

**Observation:**
- User is able to add description and also able to see description in Payment sent activity while sending cUSD and cEUR 

**Devices:** Samsung Galaxy A9 pro (8.0), Google Pixel XL (10.0), iPhone 13 mini(15.1.1), iPhone 12(14.7.1)

**Attachments:** [Mainnet.mp4](https://drive.google.com/file/d/1mH2NJbALV9ejtTsT4C-yny8gSlWkDnNW/view?usp=sharing)
[Alfajores.mp4](https://drive.google.com/file/d/1Sj4PhJDVW_bNKN4mqoFw09B-HaD07tGQ/view?usp=sharing)

Thanks..!!

**Comment by gnardini** [comment]
I disagree that this is a P0.

This is a long term existing issue. It happens because when we send a transaction we show a temporary thing in the feed that we create locally until we get the actual transfers from blockscout. These temporary (or "standby" as we call it in the code) entry has the bug above, but like I said it's an existing issue and should not block the release. It only happens because of blockscout issues.

**Comment by MuckT** [comment]
Closed in favor of #1639.
