### ISSUE TITLE
Withdrawal of CELO to External Wallet Shows as a Positive Addition

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2329]
### Current behavior
Withdrawal of Celo to an external wallet shows as a positive transaction in the transaction feed.

### Desired behavior
Celo Withdrawals should be shown as debit from a wallet.

### Steps to Reproduce
1. Navigate to add and withdraw
2. Select Celo
3. Select External Exchange
4. Complete withdrawal
5. Observe transaction feed

### Versions
unknown reproduces in 1.29.2+

### Notes
When closing and reopening the app the amount correctly displays as a debit, possibly an issue related to blockscout.

### Video
https://user-images.githubusercontent.com/26950305/163635383-94823efb-dfce-4495-a08a-ca37502a9276.mov

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Android Internal release build V:1.30.1 , V:1.29.2 and iOS internal release build V:.1.29.2, V:.1.30.1 and observed that
Observation : While confirming the payment " + " is seen however once the payment is confirmed it changes to " - " on the homepage for own address as well as for other user address

Attachment : [Android_Celo](https://drive.google.com/file/d/1FiHNtN8FLR3e9JY5C9-C3Nh7vaGcd-jn/view?usp=sharing)
[iOS_Celo](https://drive.google.com/file/d/1KK1xn1HZUpK5aeAj2i6tAvpDYcnWvxdF/view?usp=sharing)

Device : Google Pixel 2XL(11.0) , iPhone 13 mini(15.1.1)

**Comment by gnardini** [comment]
Some context:

This is a long term existing issue. It happens because when we send a transaction we show a temporary thing in the feed that we create locally until we get the actual transfers from blockscout. These temporary (or "standby" as we call it in the code) entry has the bug above, but like I said it's an existing issue and should not block the release. It only happens because of blockscout issue, so I'd say it's more of a P2 probably
