### ISSUE TITLE
Android: Home Screen balance loading bug

### ISSUE THREAD

**Issue by ellenwoconnor** [valora-inc/wallet#2386]
On android, we display first a 0, then a -, and the balance when the app is cold started. On iOS, Nitya says she doesn't see this.

**Comment by MuckT** [comment]
@ellenwoconnor are there reproduction steps for this bug?

**Comment by ellenwoconnor** [comment]
@MuckT sorry, I created the ticket and hadn't added the description yet. Let me paste in the info I've got.

**Comment by ellenwoconnor** [comment]
@MuckT this was reported by Marek. I've reached out to get any additional details on how to repro it, but haven't heard anything yet. Let me know if that's a blocker to pointing.

**Comment by ellenwoconnor** [comment]
"It happens to me on a cold boot. Either the first time after I reboot my phone or after the app gets killed after I don’t use it for a bit."

**Comment by kathaypacific** [comment]
there are a few conditions:
- slow internet
- user last opened valora more than 12 hours ago
we derive the total balance from the user's tokens + our tokens list which contains the equivalent usd price. we cache the tokens list, and update this list periodically + on certain user actions.
we have something in the app that marks the token prices as stale (if for whatever reason our backend failed to fetch token prices for 24 hours, then it doesn't make sense to show such outdated/wrong numbers in the app) if a price is stale, then we mark the token price as zero. most of the time this works well, but i think in the home feed, if your internet is slow to fetch the updated token list on app start, we'll be using the previous token list from the last session more than 12 hours ago and calculate the balance on stale (i.e. zero) token prices

the good news is, a proper loading state would fix this. we're trying to guess what is a loading state right now so you can have cases like this where there's no explicit error and the data looks legit because all the expected fields are populated (but it's wrong data)

**Comment by kathaypacific** [comment]
I think let's use this ticket to handle the loading state (i.e. when the dash appears) properly in the code. and we can create a new ticket if we want to change what loading looks like (e.g. a spinner)

**Comment by ValoraQA** [comment]
Hey @MuckT we have provided our comments on PR #2645 

thanks..
Cc: @ellenwoconnor
