### ISSUE TITLE
“Connection to Ubeswap interface was successful” blue banner appears when user tap on “Allow” button from  Transaction confirmation bottom sheet.

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#2682]
**Frequency:** 100%

**Repro on build version:** Android internal release build V1.36.0, iOS test flight release build V1.36.0
**Repro on devices:** iPhone 13 mini (15.1.1), Google Pixel XL (10.0), iPhone 12 (14.7.1), Google Pixel 4a (12.0)

**Pre-condition:** 
1.User must have completed the onboarding flow.
2.User must have valid token balance.
3. User must connected to ubeswap dapp and must be present of the ubsewap screen.

**Repro Steps:**
1.Select valid tokens from dropdown in both swap fields.
2.Tap on  enabled “Swap” & confirm swap button.
3.Tap on  “Allow” button from “Confirm transaction” bottom sheet & observe the blue banner.

**Query:** “Connection to Ubeswap interface was successful” blue banner appear when user tap on “Allow” button from  Transaction confirmation bottom sheet.

**Expected Behavior:** Valid transaction successful  blue banner must appear when user tap on “Allow” button from the Transaction confirmation bottom sheet.

**Investigation:** Same issue is reproducible while performing transaction successfully after connection of mento fi and Moola dapps to valora wallet. [Moola.mp4](https://drive.google.com/file/d/1iuKcLkyoZa38ZJKWv2l8M5MeYL-xE9cu/view?usp=sharing ) , [Mentofi.mp4](https://drive.google.com/file/d/1W5uiwH0cZKNk9MhOQLPJZ7kzuG9rwe9o/view?usp=sharing )

**Impact:** Bad user impact as incorrect success message appears on successful transaction.

**Attachment:** [Ubeswap issue.mp4](https://drive.google.com/file/d/1v19mqICTI1TC-510asl0uI8EnmtWJEAG/view?usp=sharing )

**Comment by MuckT** [comment]
@kathaypacific tagging for visibility.

**Comment by kathaypacific** [comment]
hey @MuckT @ValoraQA this behaviour has existed since implementing the in-app dapp viewer :/ what is the problem here? 

when the user "talks" to a dapp, we need some sort of feedback that the communication between wallet and dapp was successful. note that we're not tracking what type of action the user authorised, so we don't have any custom messages like "connection/approval/transaction successful". previous to the in-app dapp viewer, the same blue banner appears but says something like "connection successful, please go back to the dapp to continue". 

happy to hear suggestions of what a better experience looks like, but this would be an enhancement rather than a bug :)
