### ISSUE TITLE
Contact Support Pre-populated Emails Empty - Android API 21

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2710]
### Current behavior
When attempting to share logs with support on an API level 21 device - [Lollipop](https://en.wikipedia.org/wiki/Android_Lollipop) pre-populated email fields are empty.

### Desired behavior
Email should pre-populate with desired fields.

### Steps to Reproduce
Prerequisites: Using an Android API level 21 device (Android 5.0)
1. Create a new account using Valora.
2. Complete onboarding flow
3. Navigate to Settings > Contact
4. Fill in Support message and check that 'attach logs' is enabled
5. Tap Send
6. Select Email Client
7. Observe email client without pre-populated fields. 
 
### Versions
Android API level 21 - Possibly other android levels < 24.
All tested versions below 1.36.0

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Android Internal Release Build V1.37.0 & observed that the issue is reproducible on android version 5.

**Observation:**
- For Android 5: Contact support emails are not prepopulated & logs are not getting attached.
- For Android 6: Contact support emails are prepopulated & logs are not getting attached due to the file size is more than 25 mb 

**Devices:** Samsung Galaxy A3 (5.0.2), LG K7i (6.0)
**Attachment:** 
[Android 6.jpg](https://drive.google.com/file/d/17VF9o7kC6okCHvd5tU48getzga7PemID/view?usp=sharing)
[Android 5.jpg](https://drive.google.com/file/d/12B4NxSoueBaInu-gO1v5X2D_xMKS6uIc/view?usp=sharing)
Thanks..!!

**Comment by MuckT** [comment]
Interesting that logs file size is more than 25 mb without a large amount of use 🤔

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Android Internal Release Build V1.37.0 & observed the following:

- Contact support email have pre-populated fields & also log file is displayed attached in the email composer.

**Devices:** Google Pixel XL (10.0), Google Pixel 2XL (11.0), Google Pixel 4a (12.0)

**Attachment:** [Logs appear attached.jpg][https://drive.google.com/file/d/1joEWqbyp6gJrQJk57ZmtHqFyYqRS5CPo/view?usp=sharing]
Thanks..!!
