### ISSUE TITLE
After initial install the dapps explorer fails to load

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2754]
### Current behavior
After installing and creating a new account. The dapps explorer page fails to load any dapps.

### Desired behavior
On initial load after a fresh install the dapps page should load.

### Steps to Reproduce
1. Uninstall Valora if present on your device.
2. Install Valora and complete onboarding with a new account.
3. Navigate to Dapps List.
4. Observe Dapp List fails to load.

### Versions
v1.36.x, v1.37.x, v1.38.x, v1.39.x

### Workarounds
Close and relaunch the app.

### Notes
[Slack Thread](https://valora-app.slack.com/archives/C018VLA3YAK/p1659488561552529)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android Internal release build V:1.37.1 and iOS TestFlight Release build V:1.37.1 and observed that issue is reproducible

Attachment : [dapp.mp4](https://drive.google.com/file/d/1kTHo8W4p2y0gmxkRSR4DupG8gJ9_HLh_/view?usp=sharing)

Devices : Google Pixel 2xl(11.0), Google Pixel 4a(12.0) , iPhone 12(14.7.1) , iPhone 7(13.3)

Thanks..!

**Comment by kathaypacific** [comment]
@MuckT @ValoraQA could we please retest this, and ensure that this issue is not related to failing downstream services? there is nothing about the dapps list request that relies on the user's account creation / restore details and i have seen this downstream service being flakey before (i.e. i'd like to make sure that it is indeed a wallet issue, before we make changes in the wallet)

**Comment by MuckT** [comment]
@ValoraQA you should be able to test on the v1.39.1 release which should reproduce this bug.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android Internal Release build and Latest iOS TestFlight Release build V 1.39.1 and observed that issue is reproducible

Attachment : [iOS.mp4](https://drive.google.com/file/d/1G65KkYrPAsBH6cgKTgRe3yvoe2B2YmlZ/view?usp=sharing)
Devices : iPhone 12(16.0), Google Pixel 4a(12.0), OnePlus 7t(11.0)
