### ISSUE TITLE
Crash on Carousel Navigation

### ISSUE THREAD

**Issue by MuckT** [valora-inc/wallet#2853]
### Current behavior
During onboarding if a user quickly swipes back and forth through the navigation.

### Desired behavior
App should not crash.

### Steps to Reproduce
1. Scrolls quickly back and forth thorough the onboarding carousel.
2. Observe crash.

### Versions
Android 12 - v1.25.0 - v1.40.1

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android Internal Release build V 1.40.0 and V 1.40.1 and observed that issue is not reproducible 

Observation : Valora application is not crashing when we scroll back and forth multiple times quickly 

Device : Google Pixel 4a(12.0)

Attachment : [Carousel 1.mp4](https://drive.google.com/file/d/14_Sbbe5-5e5fa-AvzQa3JM4nIbqm_Rw-/view?usp=sharing) {Checked on V 1.40.0}

[Carousel 2.mp4](https://drive.google.com/file/d/1sntmfLUVjhuIjy3xuSw6wzNUwkY-AKSo/view?usp=sharing) {Checked on V 1.40.1}

Thanks..!

**Comment by MuckT** [comment]
@ValoraQA this still reproduces on 1.40.1 and previous builds; however, it's less frequent after the revert. If you scroll quickly back and forth through all the carousel cards. Then once the dots aren't aligned tap next you'll get a similar crash.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on Latest Android Internal Release build V 1.40.1 and observed that issue is reproducible

Observation : Application is crashing only when the dots are not seen properly aligned and in out of 5 attempts we were able to see distorting of dots only once 

Device : Google Pixel 4a(12.0)

Attachment : [carousel.mp4](https://drive.google.com/file/d/12nU7GC9PLKSNLcYIkzuKXpUxHsxfiIxF/view?usp=sharing)
[crash.mp4](https://drive.google.com/file/d/12nU7GC9PLKSNLcYIkzuKXpUxHsxfiIxF/view?usp=sharing)

Thanks..!
