### ISSUE TITLE
Validation message to check balance is not shown when user taps on Withdraw button even though user does not have enough balance.  

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#570]
**Frequency:** 100%
**Repro on build version:** Test Flight build v1.5.0 (29)
**Repro on devices:** iPhone XR (13.2.2) , iPhone 11 (14.0)
Testing Account: (806) 459-1666 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Pre-condition:**
 launch the deeplink celo://wallet/pay?address=0xd13eee43e38f65fe3839bef6297928b43de38a02&amount=.1&token=CELO 
Make sure user doesn't have enough CELO balance 

**Repro Steps:**
1. Launch the application & login with a test account.
2. Copy the given link and paste to Safari browser. 
3. Tap on Open button from "Open this page to valora" pop up
4. Make sure the Withdraw CELO screen is open.
5. Tap on the Withdraw button. 

**Current Behaviour:**  No validation message and nothing happens when the user taps on withdraw button 
**Expected Behaviour:** Users should see a validation message to check balance. 
**Impact:** User will get the idea of what went wrong. 
**Attachment:**  [IOS_NoValidationMessage.mp4	](https://drive.google.com/file/d/1vggb4XPcp7VLb9A-52hpOrEOFP6e8KY7/view?usp=sharing)(Bug Observed at 12 sec)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest iOS testflight release build V:1.29.2 and observed that "Transaction failed please retry " alert is seen if we try to send more CELO token than the balance available in the account hence we are closing this issue 

Note : Currently on deep linking the above URL , it is redirecting to send amount page (Since sending of CELO token is supported via multitoken flow) 

attachment : [alert](https://drive.google.com/file/d/1f_JJNxO_wE2oT0rT5sGOLHzeut_XVop5/view?usp=sharing)

Thanks..!!
