### ISSUE TITLE
Long notification comments overhang on the CTAs

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#579]
**Frequency:** 100%
**Repro App version:**  Android Valora Mainnet build v1.1.0 (1004294309)
**Does not repro on App version**  Test Flight build Valora app build  v1.1.0 (21) 
**Repro on device:** Samsung Galaxy A70(9.0) 
**Test Account:** Backup Key:(650) 777-7647. 
**Repro Steps:**

1. Launch the Application and sign in with a test account 
2. Tap on request button
3. Select any contact 
4. Enter valid amount 
5. Tap on review button 
6. Add long text in description 
7. Tap on request button 
8. Observe in notification 

**Current Behavior:** Text is overlapped with send button in request notification  
**Expected Behavior:** Text should fit in notification when user send request with long text
**Impact:** Bad user experience, User won't be able to read complete text on received payment request. 
**Attachment:** [TextOverlap.jpg](https://drive.google.com/file/d/1p8E-NnC8nO0xdpStavQmv20rZnf7Eh8T/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA would you please retest this can close if fixed?

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified this issue on latest iOS testflight build V: 1.23.3 and Android Internal Build V: 1.23.3 and observed that issue is fixed
Observation : Text overlapping is not seen if the description consists of long text, emoji's and also if the font size is set to max
Attachment : 
Devices :

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified this issue on latest iOS Test flight build V: 1.23.3, Android Internal Build V: 1.23.3 and observed that issue is fixed. Long description with text and emoji are not overlapping in the CTA. Hence we are closing the issue.

**Devices** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel 2 XL (11.0), Google pixel XL (10.0)
**Attachment:** [Description not overlapping.jpg](https://drive.google.com/file/d/1_eHmacLia5fRRI-3qWUx_zxwGfReq5B_/view?usp=sharing)
Thanks..!!
