### ISSUE TITLE
[Device Specific] Comma(,) is displayed instead of dot(.) for all the amounts in the amount field on the Send screen even though the app language is English.

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#584]
**Frequency:** 100%
**Repro on build version:**  Test flight build V1.10.1(46)
**Does not repro version** Android Internal build 1004294336
**Repro on devices:** Iphone SE( 13.4.1)
**Does not repro devices** Samsung A21S (D779)(SM A217F)(10) 
Testing Account:   (650-333-1978)/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)   
**Repro Steps:**
1. Launch the application & login with a test account.
2. Click on send button in home screen & select any user from searched suggestions.
3. Tap on suggested user 
4. Now user is on Send screen.
5. Now enter Decimal value.
6. Observed that,

**Current Behavior:**  Comma(,) is displayed instead of dot(.) for all the amounts in the amount field on the Send screen.
**Expected Behavior:**  Dot should be displayed to differentiate the units of the amount.
**Investigation:** Also we have observed that the comma is displayed for all amounts present in different pages/screens
**Impact:** Bad user experience.
**Attachment:**  [CommaInsteadOfDotEvenAppLangIsEnglish.png](https://drive.google.com/file/d/1DzvvMXig2ytc8Vbi0I-juFh4e89kERWP/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest test flight build V1.23.3 & observed that this issue is fixed. Dot (.) is displayed for all the amounts in the amount field on the send screen. Hence we are closing this issue.

**Device:** iPhone XS max (13.5.1)
**Attachment:** [Dot is displayed.jpg](https://drive.google.com/file/d/1C5oBZz8V25dbkhZemnHiQFjI8Oz1iTZh/view?usp=sharing)  
Thanks..!!
