### ISSUE TITLE
Add photo icon overlaps on Step 1 of 5 text on Create Account page while onboarding.

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#590]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.10.1(1004294336)
**Does not repro version** Test Flight Build V1.10.1(46)
**Repro on devices:** Samsung Galaxy A5(7.0), Samsung galaxy S7 (6.0)
**Does not repro devices** iPhone XR(14.2), Samsung Galaxy A21(10.0)
  **Repro Steps:**
1. Launch the application & tap on Create New Account.
2. Now the user should be on the “Create Account” page.
3. Now tap on Full Name field.
4. Now scroll up after the device keyboard is shown.
5. Observed that, 
**Current Behavior:**  Add photo icon overlaps on Step 1 of 5 text
**Expected Behavior:**  Icon should not overlap
**Impact:** Bad user experience.
**Attachment:**  [IconOverlapsOnStep1Of5Text.mp4](https://drive.google.com/file/d/1_qAGMLNjIzuwRFafYqCrz3UYCYy-wR0J/view?usp=sharing)

**Comment by Celoqa** [comment]
HI I have verified this issue using Playstore build V1.15.2 & observed that issue is still reproduced.
**Verified On Devices:** Samsung Galaxy J5 Prime (8.0)
**Observation:**
We have observed that Create Account Step 1 of 5 text overlaps on Add photo icon.

**Attachment:** [create account text overlaps.mp4](https://drive.google.com/file/d/1QygpsX3n5bSQgC6SA5u_J-1QUDdNIrvw/view?usp=sharing)

**Comment by Celoqa** [comment]
Hey @MuckT I have verified this issue using latest Test flight build  & Android internal build V1.17.0 & observed that issue is still reproduced.
**Observations:** Also it is observed that, overlapping happens more in 6OS device as compared to 7OS device
**Attachment:** [OverlappingOnStep1Of5.wmv](https://drive.google.com/file/d/1d36-fhk3L_QTMXEiuyELJRBkWkpXfAde/view?usp=sharing)
**Verified On Devices:** LG K7i (6.0)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest android internal release build V:1.29.2 and observed that issue is fixed

Observation :  No overlapping of issue is observed when user tries to scroll the page 
attachment : [scroll](https://drive.google.com/file/d/1uF5hsionCbD2PK5Z-iuaA064sYUuTBmV/view?usp=sharing)
Device : LG K7i (6.0)
