### ISSUE TITLE
User not able to see the full name & background color changes when user select the first name from OMNI/Suggestion box on Account info page 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#591]
**Frequency:** 100%
**Repro on build version:** Android internal Build V1.10.0(1004294335), V1.9.2,
**Repro on devices:** Samsung M30s (10) , Vivo V11 pro (10)
**Does not Repro on devices:** google pixel XL (8.1), redmi note 7 pro (10)
**Pre-condition:** Make sure Users should Enable google autofill services from settings .
 **Repro Steps:**
1. Launch the application
2. Go to account ino page
3. Place the cursor on first name filed 
4. Make sure user should see the suggestions 
**Current Behavior:** User not able to see the full name & background color changes when user select the first name from OMNI/Suggestion box on Account info page 
**Expected Behavior:** It should show full name & white background when user select any name from suggestions.
**Observation:** Content not autofilled message is shown when user try to autofill the content
**Impact:** Blocked to add full name .
**Attachment:**  [AutofillNameSuggestions.mp4](https://drive.google.com/file/d/1wZBHfp8mH5RCwACZpv4DDfsqsQWty8wO/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi I have verified this issue using latest Playstore build V1.15.2 & observed that issue is still reproduced.
**Repro on devices:** Redmi Note 8 (10.0)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue in latest android internal release build V:1.29.2  and observed the issue is fixed 
Observation :  user name is seen properly on the name field after selecting from keyboard suggestion and also from google suggestions and background color does not appear after selecting the suggestion name 
Attachment : [suggestion.mp4](https://drive.google.com/file/d/1djuxN6Ym4cJDnHi9iUxFmsohvTWYmh29/view?usp=sharing)
Device : Google Pixel 2XL(11.0)
Thanks..!!
