### ISSUE TITLE
Android: User is able to see the double account numbers on scanner page if user does not give any username

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#604]
**Frequency:** 100%
**Repro on build version:**  Android Internal Build V 1.10.1(1004294336)
**Does not repro on Version:** V1.9.2
**Repro on devices:** Samsung M30s (10),  Vivo V11 pro (10)
**Testing Account:**   (515 444 0200)/ [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)   
**Pre-condition:** User should save the name as blank.

  **Repro Steps:**

1. Launch the application & login with test account 
2. Keep user name as blank
3. Tap on scanner icon 
4. Observe

**Current Behavior:** User should able to see the account number double times on scanner page .
**Expected Behavior:** Single account number should show on scanner page .
Observation:
Only single account number is shown on scanner in iOS
**Impact:** User get confused by seeing 2 account numbers.

**Attachment:**  [DoubleAccountNumber.jpg](https://drive.google.com/file/d/1HeXg2jEIF6v_jhsoPlgGTAWWjOSMTOVL/view?usp=sharing)

**Comment by MuckT** [comment]
@ValoraQA does this issue still reproduce? If not please close.

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified this issue using latest App store build V1.19.0 , Android Internal Build V1.19.0 , found that this issue is still reproducible & observed that "Account" text appears before the 1st account address below profile icon.

**Devices:** Redmi Note 8 (10.0), iPhone 12 (14.7.1), Samsung Galaxy M31(10.0)
**Attachment:** [Account number issue.jpg](https://drive.google.com/file/d/1DvIUMZUOecvr1aq7K6-Eo810pNc9bW5s/view?usp=sharing)
