### ISSUE TITLE
Last 4 digit entered number should show in middle of input box in Confirm Account Number page 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#613]
**Frequency:** 100%
**Repro App version:** Android Internal Build v1.3.0.(1004294316) & Test Flight Build v1.3.0 (27).
**Repro on devices:** iPhone 6+ (12.4.5), Vivo V11 pro (10) 
**Account Key:** (757) 699-9899/Backup Key
**Repro Steps:** 

1. Make sure user should on spend secure page
2. Tap on Confirm Account number button
3. Enter 4 digit number on input box field 
4. Observe entered number is shown on corner  

**Suggestion:** Entered 4 digit Account number should show in middle of input box filed

**Attachment:** [Last4Digits.png](https://drive.google.com/file/d/1cKUBpDyeLLGMeDnwsbAJlqVrgyDBRybZ/view?usp=sharing)

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D439](https://valora.testquality.com/project/12128/result/2545863/defect/8743).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D454](https://valora.testquality.com/project/12128/result/2545863/defect/8762).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D884](https://valora.testquality.com/project/12128/result/2615948/defect/9687).

**Comment by ValoraQA** [comment]
https://valora.testquality.com defect [D897](https://valora.testquality.com/project/12128/result/2613005/defect/9707).

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue on Latest Android Internal Release Build, iOS Test flight Release Build V1.32.0 & observed that the issue is fixed now.

- Last 4 digits of the address entered are displayed in the middle of the input box on Confirm account address screen.  

Hence we are closing this issue.

**Devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1), Google Pixel XL (10.0)
**Attachment:** [Send secure address.mp4](https://drive.google.com/file/d/1ihXynB2qnKiyNBu6GfmbFMYUPIDZkMc2/view)
Thanks..!!
