### ISSUE TITLE
Currency conversion rate does not update when internet connection is lost and restored

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#621]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.0.0 (17) , Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 
**Test Account:** Backup Key: (757) 699-9899. 

**Repro Steps:**
1. Launch the Application and sign in with test account
2. Navigate to Setting screen by tapping on hamburger > Setting option. 
3. Turn OFF the internet connection. 
4. Tap on Currency option. 
5. Change the currency Ex. USD to CAD. 
6. Tap on the Hamburger menu. 
7. Turn on the internet connection
8. Observe. 

**Current Behavior:** “-” is shown instead of balance
**Expected Behavior:**  Balance should be shown. 
**Investigation:** 
- Balance is shown after cold launch the app. 
- Issue is repro for every currency. 
**Impact:** User may get frustrated after seeing - instead of balance. 
**Attachment:** [BalanceIssue.mp4](https://drive.google.com/file/d/1MRuj4Fe6sKRN9wrb9Z2ONsouFmHn7ZpN/view?usp=sharing) (Bug observe at 36 sec)

**Comment by Celoqa** [comment]
Hi @jeanregisser I have verified this issue using latest Android Internal Build V1.15.2 & Test Flight Build V1.15.2(65) &observed that issue is still reproduced.
Currency conversion rate does not update for CELO from Menu when internet connection is lost and restored
**Verified on devices:** Vivo v11 pro (10) , iPhone 6+ (12.4.5)
