### ISSUE TITLE
Make wallet exchange more predictable

### ISSUE THREAD

**Issue by cmcewen** [valora-inc/wallet#792]
### Expected Behavior

~We have seen a few instances of exchange transactions reverted in the wallet. We should update params to make this more reliable.~

EDIT: see conversation below.

**Comment by jeanregisser** [comment]
I took a deep look at #662 and it has a couple of issues.
>The `exchangeGoldAndStableTokens` function doing the actual contract calls became quite difficult to understand and, in the current state of this PR, is not correct.
For instance it's not approving the right amounts, approving too much: if I sell 1 cUSD worth of CELO, it's approving to sell up to 1 CELO (:scream: ). Good thing we didn't ship this :smile:

I think the main issue we had was fixed in #1268
In the current state of things it's not worth making the changes to the `buy` and `sell` methods now.
Exchanging currently works reliably and it would be better to revisit this when we'll build a more generic exchange screen supporting multiple tokens instead of just CELO/cUSD/cEUR.

**Comment by jeanregisser** [comment]
Also when we actually switch to `buy` / `sell` contract methods we should probably consider updating the exchange rate logic too, to use `quoteStableBuy` , `quoteStableSell`, `quoteGoldBuy` and `quoteGoldSell`.
But I'm not entirely familiar with these and we should investigate what is "the way" to do it properly ;)

**Comment by ellenwoconnor** [comment]
@jeanregisser @gnardini can we make a note of this and close it out? It seems like something we can cover with in app exchange, just want to make sure the issue is noted as something to watch out for

**Comment by gnardini** [comment]
Yup, closing this one, since it will be replaced with whatever we use for in-app exchanges.
