### ISSUE TITLE
Prevent withdraw button from being able to be pressed twice on the Celo withdraw flow

### ISSUE THREAD

**Issue by gnardini** [valora-inc/wallet#939]
### Current behavior
The withdraw button can be pressed more than once which could cause a transaction to be sent twice if the user presses the button more than once.

### Desired behavior
The withdraw button can only be pressed once.

### Steps to Reproduce
Try to withdraw Celo and press the button very quickly. It's hard to reproduce.

### Versions
Any

**Comment by Celoqa** [comment]
Hey @gnardini I have verified this issue using latest Test flight build & Android internal build V1.17.0 & observed that issue is reproduced for us.
**Observations:** 

- We have observed issue after tapping twice on "Withdraw" button quickly. And also observed transaction happens twice with deducting same balance two times.
**Attachment:**  [TransactionTwoTimesAfterTappinWithdrawTwoTimes.mp4](https://drive.google.com/file/d/173do0hhgeFSHh_KA3PK2uniTNTHuaZmO/view?usp=sharing)
**Verified On Devices:** Redmi Note 8 (9.0)
